services:
  my-app:
    build: .
    image: my-script:latest
    container_name: my-app
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - monitor-data:/var/www

volumes:
  monitor-data:
    name: my-script-monitor-data
